options:
  juju-gui-source:
    description: |
      Where to install Juju GUI from. Possible values are:
      - 'stable' (default): the latest stable release will be deployed;
      - 'trunk': the latest trunk release will be deployed;
      - a stable version (e.g '0.1.0'): the specified stable version will be
        deployed;
      - a trunk version (e.g '0.1.0+build.1'): the specified trunk version
        will be deployed;
      - a Bazaar branch (e.g. 'lp:juju-gui'): a release will be created and
        deployed from the specified Bazaar branch.
    type: string
    default: stable
  juju-api-branch:
    description: |
      The Juju API Bazaar branch (implementing the websocket server).
    type: string
    default: lp:~hazmat/juju/rapi-rollup
  juju-api-port:
    description: |
      The port used by the websocket server.
    type: int
    default: 8080
  staging:
    description: |
      Connect the Juju GUI to the staging backend
      (i.e. a simulated Juju environment).
    type: boolean
    default: false
  staging-environment:
    description: |
      The environment JSON export used by the staging server. This option can
      be used to change the topology of the simulated Juju environment.
      Possible values are 'sample' and 'large'.
    type: string
    default: sample
  juju-gui-console-enabled:
    description: |
      Whether or not the console should be enabled for the browser.
    type: boolean
    default: false
  command-log-file:
    description: |
      The log file where stdout and stderr should be sent for all
      commands that are run by charm hooks.
    type: string
    default: /var/log/juju/juju-gui.log
  ssl-cert-path:
    description: |
      The path to the directory where the SSL certificates are stored.
    type: string
    default: /etc/ssl/private/juju-gui
  ssl-cert-contents:
    description: |
      The contents of the certificate file to be used in SSL connections to
      the GUI. Both ssl-cert-contents and ssl-key-contents must be provided.
      If not, cetificates will be automatically generated.
    type: string
  ssl-key-contents:
    description: |
      The contents of the private key file to be used in SSL connections to
      the GUI. Both ssl-cert-contents and ssl-key-contents must be provided.
      If not, cetificates will be automatically generated.
    type: string
