options:
  juju-gui-branch:
    description: |
      The Juju GUI Bazaar branch containing the source code to be deployed.
    type: string
    default: lp:juju-gui
  juju-improv-branch:
    description: |
      The Juju Bazaar branch containing the improv script.
    type: string
    default: lp:~hazmat/juju/rapi-rollup
  juju-gui-console-enabled:
    description:
      Whether or not the browser's console should be enabled.
    type: string
    default: 'false'
