options:
  juju-gui-branch:
    description: |
      The Juju GUI Bazaar branch containing the source code to be deployed.
    type: string
    default: lp:juju-gui
  juju-improv-branch:
    description: |
      The Juju Bazaar branch containing the improv script. This value is only
      used if the staging option is set to True.
    type: string
    default: lp:~hazmat/juju/rapi-rollup
  staging:
    description: |
      Connect the Juju GUI to the staging backend (i.e. the improv script).
    type: boolean
    default: False
