options:
  juju-gui-branch:
    description: |
      The Juju GUI Bazaar branch containing the source code to be deployed.
    type: string
    default: lp:juju-gui
  juju-api-branch:
    description: |
      The Juju API Bazaar branch (implementing the websocket server).
    type: string
    default: lp:~hazmat/juju/rapi-rollup
  juju-api-port:
    description: |
      The port used by the websocket server.
    type: int
    default: 8080
  staging:
    description: |
      Connect the Juju GUI to the staging backend
      (i.e. a simulated Juju environment).
    type: boolean
    default: False
  staging-environment:
    description: |
      The environment JSON export used by the staging server. This option can
      be used to change the topology of the simulated Juju environment.
      Possible values are 'sample' and 'large'.
    type: string
    default: sample
  juju-gui-console-enabled:
    description: |
      Whether or not the console should be enabled for the browser.
    type: boolean
    default: false
  command-log-file:
    description: |
      The log file where stdout and stderr should be sent for all
      commands that are run by charm hooks.
    type: string
    default: /var/log/juju/juju-gui.log
  ssl-cert-path:
    description: |
      The path to the directory where the SSL certificates are stored.
    type: string
    default: /etc/ssl/private/juju-gui
