options:
  juju-gui-branch:
    description: |
      The Juju GUI Bazaar branch containing the source code to be deployed.
    type: string
    default: lp:juju-gui
  juju-api-branch:
    description: |
      The Juju API Bazaar branch (containing the improv script).
    type: string
    default: lp:~hazmat/juju/rapi-rollup
  juju-api-port:
    description: |
      The port used by the websocket server.
    type: int
    default: 8080
  staging:
    description: |
      Connect the Juju GUI to the staging backend (i.e. the improv script).
    type: boolean
    default: False
  staging-environment:
    description: |
      The environment JSON export used by the staging server.
      Possible values are 'sample' and 'large'.
    type: string
    default: sample
  juju-gui-console-enabled:
    description: |
      Whether or not the browser's console should be enabled.
    type: boolean
    default: false
